services:
  backend:
    image: bektigalan/test:latest
    container_name: backend-api
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-dashboard
    ports:
      - "7013:80"                     # ← 7000 + 13 (nomor urut)
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

networks:
  app-network:
    driver: bridge